### ISSUE TITLE
Don't auto update submodules to HEAD

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/cross-language-cpp.github.io#10]
Currently every night an action is executed, that pulls the latest HEAD of each submodule. In case of the djinni-generator this recently had the effect that documentation for a unreleased change was published.

As a user I'd like the website to always show the documentation of the latest *released* version of each component. I'd also like to see which version of the component is currently documented (maybe with a small badge on the top of the page, that shows the version of the component + a link to the release).
Optionally I'd like to be able to switch to the documentation of an older version of the component-documentation.

**Comment by jothepro** [comment]
This has implication that I don't like. If only the latest release docs are published, the docs cannot be patched any more. Every small fix in the docs would require a new release :/

**Comment by a4z** [comment]
It is true that patching docs would require a new version but that is the case anyway

If you have version 1.0 , and want to update the doc for that , how do you do that (without an extra branch)
so, you have 1.0, and master

master is the latest state, 1.0 that one for the 1.0 release.
you patch in master, always, except we want release branches 

master docs should still be visible in the docs.

the landing page should point to the latest release.
if this is all possible without creating an insane huge workload ...
